BACKOFFICE FE/UI/Labeling Tool: Update UI/UX re-render image after up…
ocmg-it/make-sense pull request #27
Opened 2022-10-24 09:51 UTC by cuongho2

Set border of image to red if status = R
After user click upload → re-render image object

2022-10-24 12:19 UTC, choipd requested changes
There are some minor issues.

2022-10-24 12:19 UTC, choipd commented on src/store/labels/actionCreators.ts
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/store/labels/reducer.ts
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/EditorContainer/EditorContainer.tsx
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/EditorContainer/EditorContainer.tsx
> +                           // console.log('style == ', style);
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/EditorContainer/EditorContainer.tsx
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/SideNavigationBar/ImagePreview/ImagePreview.tsx
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/SideNavigationBar/ImagePreview/ImagePreview.tsx
> +
[minor] Please do not edit unrelated code

2022-10-24 12:19 UTC, choipd commented on src/views/EditorView/SideNavigationBar/ImagesList/ImagesList.tsx
> +
[minor] Please do not edit unrelated code

2022-10-25 01:17 UTC, cuongho2 commented
hi mr @choipd, I was removed unrelate code.

2022-10-25 01:48 UTC, choipd commented on src/views/EditorView/EditorContainer/EditorContainer.tsx
> +                        // console.log('style == ', style);
It would be nice if you kept the previous code when it is not related to this PR.

2022-10-25 07:04 UTC, cuongho2 commented
Mr @choipd , I was fixed all your mentain, Could you approve my new code.

2022-10-25 07:05 UTC, merged

2022-10-25 07:06 UTC, choipd commented
@cuongho2 I've merged, Thanks